README.md
Update the link of the GitHub Actions build status badge (Build Status) so that it reflects the build status of the team repo.
=> Update readme 1

README.md, docs/DeveloperGuide.md
Complete A3 by acknowledging the original source of the code.
=> Edit readme

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Phone.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/PhoneTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Ready for review
Closes #37 
Implement 'add contact' feature as per specifications in feature list
- Add line break to make format results message more readable for add contact success
- Trim all whitespaces for phone number inputs
- Add constrain to phone number input to ensure all phone numbers are 8 digits long
- Update test cases for phone number
- Update test persons to fit new constrains on phone number
- Update user guide for add feature
- Feature specification does not use 'n/' prefix for name like AB3 does, discuss if this is what we want
=> Add contact feature

src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java, src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Close #40 
Find a contact by name, or phone, but not both.
Future implementation:
- match characters, not just whole word
=> Find command: search by phone

src/main/java/seedu/address/ui/HelpWindow.java
Update HelpWindow link to MediContact userguide link
=> Update HelpWindow link

src/main/java/seedu/address/logic/commands/EditCommand.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java
- Updated logic in `EditCommand` file
- Updated relevant tests
Fixes #64
=> Fixes bug where tags and appointments were overridden accidentally

docs/UserGuide.md, src/main/java/seedu/address/ui/HelpWindow.java
closes #81 
Update command summary table in UserGuide and HelpWindow to include newly added commands from PR #79
=> Update command summary

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/ExportCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/ui/HelpWindow.java, src/test/java/seedu/address/logic/commands/ExportCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
closes #83 
Exports addressbook.json to users local device under data/addressbook.json upon command `export`
- Add ExportCommand
- Add tests
- Update user guide & help window command summary
- Make UI more intuitive (e.g. pop-up window with more detailed notes on where user can find their addressbook.json file)
=> Export feature

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/appointment/Appointment.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/ui/HelpWindow.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/SortCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/SortCommandParserTest.java, src/test/java/seedu/address/model/appointment/AppointmentTest.java
Add sort command to sort on basis of appointment dates
=> Sort Command

docs/DeveloperGuide.md, docs/diagrams/ParserSubClasses.puml
Added new class diagram for Parser Subclasses
=> Add Class Diagram for Parser Classes to DG

docs/DeveloperGuide.md, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/DeleteSequenceDiagram.puml, docs/diagrams/UiClassDiagram.puml
Closes #92 
Update content and diagrams in developer guide
Diagrams updated are:
- ArchitectureSequenceDiagram
- DeleteSequenceDiagram
- UiClassDiagram
=> Update content and diagrams in developer guide

docs/diagrams/StorageClassDiagram.puml
New classes JsonAdaptedNote and JsonAdaptedAppointments were added to reflect new Storage class interactions
#95
=> Update Storage's .puml file to reflect new fields

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/main/java/seedu/address/model/person/PersonWithCriteriaPredicate.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java, src/test/java/seedu/address/model/person/PersonWithCriteriaPredicateTest.java, src/test/java/seedu/address/model/tag/TagTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
In addition to filtering person list by appointment dates and age range, users can filter by tags using `t\`.
**New Features added**
- filter by tags
- tags is matched in case-insensitively
- change tags in sample data with medical-related tags 
**Screenshots**
**Future to-dos**
Identify potential bugs and fix them.
close #99
=> Filter by tags

src/main/java/seedu/address/logic/commands/ClearCommand.java
Fix confirmation alert not triggered for clear command
Closes #115
=> Fix confirmation alert not triggered for clear command

docs/DeveloperGuide.md, docs/UserGuide.md
Added the following
- Manual test cases for each testable feature
- Added appendix section for effort (anyone can feel free to add anything they thing is relevant)
- Added appendix section for future enhancements
**To do**
Everyone is to add in their 2 enhancements that they think is needed. This will help protect us against bugs that other teams find during the PE
#48
=> Update DG for v1.5

src/main/java/seedu/address/ui/ConfirmationWindow.java
Ready for review
Fix unusual behaviour of confirmation window when in fullscreen
Screenshot of updated behaviour:
Fixes #130
=> Fix unusual behaviour of confirmation window when in fullscreen

docs/UserGuide.md
Ready for review
Fixes #145, #146
User guide example json format was missing curly brackets and example person format missing starredStatus. Updated to ensure expected format is reflected correctly. Improve user guide for person data.
=> Fix issue 145 and 146

src/main/java/seedu/address/logic/commands/NoteCommand.java, src/main/java/seedu/address/logic/parser/ImportCommandParser.java, src/main/java/seedu/address/logic/parser/NoteCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/appointment/Appointment.java, src/main/java/seedu/address/model/note/Note.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/NoteCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java, src/test/java/seedu/address/model/appointment/AppointmentTest.java, src/test/java/seedu/address/model/note/NoteTest.java
This pull request will fix the following bugs
- Past appointments not sorted
- Note will only accept appointment prior to current time
- Add and Edit will only accept appoints after current time
- Updated Note command result display
- Updated Note appointment error message
- Updated Edit and Add appointment error message
Fixes #120 #140 #154 #155
=> Fix alpha bugs found regarding Notes and Appointments

src/main/java/seedu/address/logic/commands/ImportCommand.java, src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Reading for review
Fixes #158 
There's a lot of repetition in note validation method. Since Note::isValidAppointment now takes in a string, let's increase modularity for note validation.
=> Update import command parser

src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/test/java/seedu/address/logic/commands/FilterCommandTest.java, src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Resolve reported bugs on Filter Command
**Features Added**
1. Update error messages for invalid range, and no matches found
2. Edit message usage
**Screenshots**
close #110 #109 #121
=> Filter Command: resolve bugs

src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/logic/parser/ViewCommandParser.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/resources/view/LightTheme.css, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Resolve bugs reported for view command.
**Main Changes**
1. Resolve wrong error message issue
2. Disable clicking event on UI person card, which means notes will not on click
**Screenshots**
close #156  #128 #142
=> Resolve bugs: View Command

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Resolve bugs reported for Edit Command.
**Main Changes**
1. Check validity of name before checking remaining format.
2. Update relevant tests
**Screenshots**
close #134
=> Fix issue: Edit Command

docs/UserGuide.md, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/ImportCommand.java, src/main/java/seedu/address/logic/commands/NoteCommand.java, src/main/java/seedu/address/logic/commands/StarCommand.java, src/main/java/seedu/address/logic/commands/UnstarCommand.java, src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/StarCommandTest.java, src/test/java/seedu/address/logic/commands/UnstarCommandTest.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java, src/test/java/seedu/address/model/person/PersonTest.java
Sorry I branched off of a branch used in an unmerged commit, so some of the file changes belong to PR #172 
Messages currently have inconsistencies. Let's make messages consistent. No change to behaviour of application (aside from the minor changes to message usage for consistency). Just tidying up the code. 
- Fix error in `Edit` message usage
- Modify `Delete`, `Star`, `Unstar` and `View` to use Messages class for invalid name or index.
- Fix some minor inconsistencies in messages between the different commands.
=> Make messages consistent

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/EditCommand.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java
- Update Developer Guide to reflect new implemented behavior
- Update User Guide to clarify how to edit tags / appointments
- Implemented error message which reflects when no changes are detected (If at least one change is detected, error is not triggered)
Fixes #151 
Fixes #153
=> Update Edit Command to fix alpha bugs

src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/ui/controller/ConfirmationBypassController.java, src/main/java/seedu/address/ui/controller/ConfirmationController.java, src/main/java/seedu/address/ui/controller/ConfirmationWindowController.java, src/main/resources/view/LightTheme.css, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/commands/ClearCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Improve UI and move folder
- Change colours in the app to follow the chosen colour palette
- Increase the font size of most text to fulfil a user story
- Change minor parts of UI
- Move controller to UI as it is part of UI
Fixes #171
=> Improve UI and move folder

docs/stylesheets/main.css
Update the color theme of UG and DG headers to make it more cohesive with our product.
=> Update UG color palette

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/DeleteSequenceDiagram.puml, docs/diagrams/LogicClassDiagram.puml, src/main/java/seedu/address/logic/commands/ClearCommand.java
Update Developer Guide, fix User Guide bug and rename a method
Fixes #177
=> Update Developer Guide, fix User Guide bug and rename a method

docs/stylesheets/main.css
Increase font size by 0.4rem for UG and DG pdf. Size of image remains the same.
(Please merge asap so we can see how it looks like and make changes if needed)
#49
=> Increase font size

docs/UserGuide.md
Formatted the styling of the UG. 
Changed the language of the UG to be catered to the target audience.
=> Updated User Guide Styling

docs/DeveloperGuide.md
=> edit acknowledgement

docs/DeveloperGuide.md
Updated use cases language to be more target audience specific
=> Update DG: Make Use cases more target audience specific

docs/DeveloperGuide.md, docs/UserGuide.md
=> Add to FAQ and glossaries

docs/diagrams/FilterActivityDiagram.puml
=> Resolve typo
